apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: {{ .Chart.Name }}-coffee
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: {{ .Chart.Name }}-tea
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - containerPort: 8080
